apiVersion: v1
kind: Service
metadata:
  name: agenyx-orchestrator
  namespace: agenyx
  labels:
    app.kubernetes.io/name: agenyx-orchestrator
    app.kubernetes.io/part-of: agenyx

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: agenyx-orchestrator

  ports:
    - name: http
      port: 8002
      targetPort: http
      protocol: TCP
