apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: agenyx-valkey
  namespace: agenyx

spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: valkey

  policyTypes:
    - Ingress

  ingress:
    # Orchestrator
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: agenyx-orchestrator
      ports:
        - protocol: TCP
          port: 6379

    # Worker
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: agenyx-worker
      ports:
        - protocol: TCP
          port: 6379

    # Router
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: agenyx-router
      ports:
        - protocol: TCP
          port: 6379
