apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agenyx-alloy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agenyx-alloy
subjects:
  - kind: ServiceAccount
    name: agenyx-alloy
    namespace: monitoring
