apiVersion: v1
kind: Service
metadata:
  name: agenyx-router
  namespace: agenyx
  labels:
    app.kubernetes.io/name: agenyx-router
    app.kubernetes.io/part-of: agenyx
spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: agenyx-router

  ports:
    - name: http
      port: 8005
      targetPort: http
      protocol: TCP
