apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agenyx-router
  namespace: agenyx
  labels:
    app.kubernetes.io/name: agenyx-router
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: agenyx-router

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s
