apiVersion: v1
kind: Service
metadata:
  name: agenyx-otel-collector
  namespace: monitoring
  labels:
    app.kubernetes.io/name: agenyx-otel-collector
    app.kubernetes.io/part-of: agenyx

spec:
  selector:
    app.kubernetes.io/name: agenyx-otel-collector

  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
      protocol: TCP

    - name: otlp-http
      port: 4318
      targetPort: otlp-http
      protocol: TCP
