apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: agenyx-agent
  namespace: agenyx
  labels:
    app.kubernetes.io/name: agenyx-agent
    app.kubernetes.io/part-of: agenyx

spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: agenyx-agent

  policyTypes:
    - Ingress
    - Egress

  ingress:
    # Allow traffic from the Agenyx gateway.
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: agenyx-gateway

      ports:
        - protocol: TCP
          port: 8000

    # Allow traffic from other Agenyx components.
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: agenyx

      ports:
        - protocol: TCP
          port: 8000

  egress:
    # DNS.
    - to:
        - namespaceSelector: {}

      ports:
        - protocol: UDP
          port: 53

        - protocol: TCP
          port: 53

    # Agenyx internal services.
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: agenyx

      ports:
        - protocol: TCP
          port: 8005

        - protocol: TCP
          port: 8004

        - protocol: TCP
          port: 8000

        - protocol: TCP
          port: 9000
