apiVersion: v1
kind: Service
metadata:
  name: agenyx-agent
  namespace: agenyx
  labels:
    app.kubernetes.io/name: agenyx-agent
    app.kubernetes.io/part-of: agenyx

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: agenyx-agent

  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
