apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agenyx

resources:
  - configmap.yaml
  - serviceaccount.yaml
  - service.yaml
  - deployment.yaml
  - networkpolicy.yaml
  - servicemonitor.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: agenyx
    includeSelectors: false
